# Generated by Django 4.2.9 on 2024-02-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['-time_create'], name='sport_site__time_cr_671c85_idx'),
        ),
    ]
