# Generated by Django 4.2.9 on 2024-02-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0006_alter_sport_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sport',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='sport_site.category'),
        ),
        migrations.AddField(
            model_name='sport',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sport_site.tagpost'),
        ),
    ]
