# Generated by Django 4.2.9 on 2024-02-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0007_tagpost_alter_sport_cat_sport_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soulmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='soulmate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_mate', to='sport_site.soulmate'),
        ),
    ]
