# Generated by Django 4.2.9 on 2024-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0008_soulmate_sport_soulmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulmate',
            name='w_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
