# Generated by Django 4.2.9 on 2024-02-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0009_soulmate_w_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['-time_create'], 'verbose_name': 'famous sportsmen', 'verbose_name_plural': 'famous sportsmen'},
        ),
        migrations.AddField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='sport_site.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'draft'), (True, 'published')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='soulmate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_mate', to='sport_site.soulmate', verbose_name='soulmate'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sport_site.tagpost', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
