# Generated by Django 4.2.9 on 2024-02-20 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_site', '0010_alter_category_options_alter_sport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['time_create'], 'verbose_name': 'famous sportsmen', 'verbose_name_plural': 'famous sportsmen'},
        ),
        migrations.AddField(
            model_name='sport',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
